### ISSUE TITLE
Duplicate OneToMany or any other relations

### ISSUE THREAD

**Issue by walter211** [Kononnable/typeorm-model-generator#101] opened 2018-09-20 05:55 UTC
@Entity("speaker",{schema:"scf"})
export class speaker {

    @Column("varchar",{ 
        nullable:false,
        length:1000,
        name:"bio"
        })
    bio:string;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        default:"",
        name:"blog"
        })
    blog:string;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        name:"companyname"
        })
    companyname:string;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        default:"",
        name:"companytitle"
        })
    companytitle:string;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        default:"",
        name:"companywebsite"
        })
    companywebsite:string;
        

    @Column("timestamp",{ 
        nullable:false,
        default:"CURRENT_TIMESTAMP(6)",
        name:"createdAt"
        })
    createdAt:Date;
        

    @PrimaryGeneratedColumn({
   
        name:"id"
        })
    id:number;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        name:"name"
        })
    name:string;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        name:"phonenumber"
        })
    phonenumber:string;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        default:"",
        name:"twitter"
        })
    twitter:string;
        

    @Column("timestamp",{ 
        nullable:false,
        default:"CURRENT_TIMESTAMP(6)",
        name:"updatedAt"
        })
    updatedAt:Date;
        

    @Column("varchar",{ 
        nullable:false,
        length:255,
        default:"",
        name:"website"
        })
    website:string;
        

   
    @OneToMany(type=>session, session=>session.speaker,{ onDelete: 'NO ACTION' ,onUpdate: 'NO ACTION' })
    sessions:session[];
    

   
    @OneToMany(type=>session, session=>session.speaker,{ onDelete: 'NO ACTION' ,onUpdate: 'NO ACTION' })
    sessions2:session[];
    
}

**Comment by Kononnable** [comment] 2018-09-24 19:41
Please provide DDL statements - there is no way of telling whats wrong by just looking on the generated model.

**Comment by ndarilek** [comment] 2018-10-17 17:07
I'm seeing this too, using MSSQL. Here's the table definition. Apologies for the mess--legacy database gonna legacy:

```
/****** Object:  Table [dbo].[users]    Script Date: 10/1/18 8:41:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[UserID] [int] NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[MiddleIn] [varchar](1) NOT NULL,
	[LastName] [varchar](145) NOT NULL,
	[SecondLastName] [varchar](145) NOT NULL,
	[NickName] [varchar](50) NULL,
	[PublicBio] [varchar](4000) NULL,
	[GenderID] [int] NOT NULL,
	[PreferredLanguageID] [int] NOT NULL,
	[PreferredCountryID] [int] NOT NULL,
	[IsProvider] [bit] NOT NULL,
	[IsCustomer] [bit] NOT NULL,
	[IsAdmin] [bit] NOT NULL,
	[IsCollaborator] [bit] NOT NULL,
	[Photo] [varchar](150) NULL,
	[MobilePhone] [varchar](20) NULL,
	[AlternatePhone] [varchar](20) NULL,
	[CanReceiveSms] [bit] NOT NULL,
	[ProviderProfileURL] [varchar](2078) NULL,
	[ProviderWebsiteURL] [varchar](2078) NULL,
	[SMSBookingCommunication] [bit] NOT NULL,
	[PhoneBookingCommunication] [bit] NOT NULL,
	[LoconomicsMarketingCampaigns] [bit] NOT NULL,
	[ProfileSEOPermission] [bit] NOT NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[ModifiedBy] [varchar](50) NULL,
	[Active] [bit] NULL,
	[LoconomicsCommunityCommunication] [bit] NOT NULL,
	[IAuthZumigoVerification] [bit] NULL,
	[IAuthZumigoLocation] [bit] NULL,
	[LoconomicsDBMCampaigns] [bit] NOT NULL,
	[AccountStatusID] [int] NOT NULL,
	[CoBrandedPartnerPermissions] [bit] NOT NULL,
	[MarketingSource] [varchar](2055) NULL,
	[BookCode] [varchar](64) NULL,
	[OnboardingStep] [varchar](60) NULL,
	[BirthMonthDay] [int] NULL,
	[BirthMonth] [int] NULL,
	[BusinessName] [nvarchar](145) NULL,
	[AlternativeEmail] [nvarchar](56) NULL,
	[ReferredByUserID] [int] NULL,
	[SignupDevice] [nvarchar](20) NULL,
	[OwnerStatusID] [int] NULL,
	[OwnerAnniversaryDate] [datetime] NULL,
	[IsHipaaAdmin] [bit] NOT NULL,
	[IsContributor] [bit] NULL,
	[TrialEndDate] [datetimeoffset](7) NULL,
	[BirthYear] [int] NULL,
	[IsOrganization] [bit] NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```

This generates the following snippet in users.ts:

```
@Entity("users",{schema:"dbo"})
export class users {

   
    @OneToOne(type=>users, users=>users.users,{ primary:true, nullable:false, })
    @JoinColumn({ name:'UserID'})
    user:Promise<users | null>;

    @OneToOne(type=>users, users=>users.users2,{ primary:true, nullable:false, })
    @JoinColumn({ name:'UserID'})
    user:Promise<users | null>;

...
```

Not sure why that primary key generates a duplicate relation and not a primary key. I'm also not sure if any command line flags might help. I basically hate MSSQL very deeply, don't really know what I'm doing, and am trying to wrangle this legacy schema into an ORM so we can actually start using migrations and, eventually, maybe move to something more sane like Postgres. :) So I can provide other bits of our schema if needed, but I'm much more comfortable/competent with open source databases than I am with MSSQL and don't really know what I'm doing in this specific case.

Thanks for any help. Wondering if there's anyone we can throw modest amounts of money at to wrangle our existing schema into TypeORM models/migrations that we can use going forward.

**Comment by Kononnable** [comment] 2018-10-21 20:30
@ndarilek It looks like it want to generate some kind of self-join. Not sure why - schema generated by query you send generates just columns - no  relations. So there are probably some more foreign keys in your database.
As for moving from mssql to postgres - real pain in such migration are database objects(functions, procedures). If you use them you have to rewrite them manually. Tables - column types and data migration can be easily done by some free software.

**Comment by ndarilek** [comment] 2018-10-22 17:00
I can send you the entire schema if it'd be helpful, though it's about 
280K. It does give lots of what appears to be junk data in the models, 
though, so might be more useful than a single table definition.

**Comment by Kononnable** [comment] 2018-10-27 10:43
Sorry for delay. Entire schema should work, or full schema for users table and simplified for related tables(just to make relation works) - whichever you prefer.

**Comment by ndarilek** [comment] 2018-10-29 19:15
Thanks! https://uxhftlxbcms3zxj3vzp8.nolan.sandcats.io/schema.sql is our current schema. It generates duplicate relations and odd foreign key relationships in the `user` model. Please let me know if you need any other details--I'm much more familiar with non-MSSQL DBMSs so don't know if there are other details that would help.

**Comment by ndarilek** [comment] 2018-10-30 21:30
Good question, let me ping my coworker. @IagoSRL, any thoughts? I'd like to use this project to transition us to an ORM. If you can help us to resolve any issues with our schema, that would be hugely helpful. :) Thanks!

**Comment by IagoSRL** [comment] 2018-10-30 23:08
Hi @ndarilek, that FKs are as useless as they seem. I have removed them from my local right now and going to remove them from dev and production.

They name given to them follows the pattern used by MSSMS when adding new keys (that by default uses self-referenced values just after clicking, who knows why); so looks like adding several new keys, someone forgot to replace default values at some rows. Silly, right? Sorry on behalf of the project for the time lost.

**Comment by ndarilek** [comment] 2018-10-31 19:58
Cool, thanks! I can confirm that removing those lines from my copy of the schema SQL dump resolved those issues.

As an aside, we're still getting some odd issues, and I'm not sure whether they're to do with our schema or with the model generator. As an example:

```
@Entity("booking",{schema:"dbo"})
export class Booking {

...
    @ManyToOne(type=>Cancellationpolicy, Cancellationpolicy=>Cancellationpolicy.bookings2,{  nullable:false, })
    @JoinColumn({ name:'LanguageID'})
    language:Cancellationpolicy | null;
...
```

Lots of our relations are called `language` but they return completely different entities, and I don't know if this is another schema issue, or something in typeorm-model-generator.

That's not strictly related to this issue, but if the fix isn't glaringly obvious, are you or anyone else available for hire to wrangle our schema into something that typeorm-model-generator can generate classes for so we can start using an ORM/migrations going forward? Or, if you aren't, do you know anyone who can help? I'm more familiar with Postgres/MySQL than with SQLServer, so I'm in a bit over my head with this. I just want to export our current schema to TypeScript models so we can use best practices moving forward.

Thanks.

**Comment by Kononnable** [comment] 2018-11-19 22:14
@ndarilek sorry for leaving you like that(without more help, even reply). I had a lot on my mind lately and didn't had the time to work on OSS. 
I won't probably have much time during next two weeks, but I will try to spend some to help.

**Comment by Kononnable** [comment] 2018-12-29 21:56
Closing as original author didn't provide schema to reproduce the issue. May be connected to #130.
@ndarilek If you still got issues let me know.

**Closed by Kononnable** 2018-12-29 21:56 UTC
