### ISSUE TITLE
broken entity code generated using with mysql datatype 'set'

### ISSUE THREAD

**Issue by godhelpjun** [Kononnable/typeorm-model-generator#200] opened 2019-09-06 03:46 UTC
@Column("set",{ 
        nullable:false,
        name:"flag"
        })
    flag:;   //illegal syntax here in this line will cause tsc stop 

fa_category.ts(54,10): error TS1110: Type expected

**Comment by Kononnable** [comment] 2019-09-09 19:41
Could you provide DDL statements to reproduce the issue?

**Comment by godhelpjun** [comment] 2019-09-12 07:29
create table fruit(names set('apple','bananna','grape'));

**Comment by CatsMiaow** [comment] 2019-09-16 04:04
https://github.com/Kononnable/typeorm-model-generator/issues/91

**Comment by Kononnable** [comment] 2019-09-16 19:50
Duplicate of #91, lets keep this in one issue.

**Closed by Kononnable** 2019-09-16 19:50 UTC
Labels: duplicate, enhancement
