### ISSUE TITLE
Creating relations twice on each model.

### ISSUE THREAD

**Issue by amfsyn** [Kononnable/typeorm-model-generator#89] opened 2018-07-23 11:13 UTC
I just created models for all of the tables in my MySQL db and for each model, each relation is created twice, identically.
```
@ManyToOne(type=>orgs, orgs=>orgs.synalertss,{  nullable:false,onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'org_id'})
    org_:orgs | null;

@ManyToOne(type=>orgs, orgs=>orgs.synalertss2,{  nullable:false,onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'org_id'})
    org_:orgs | null;

@ManyToOne(type=>object_types, object_types=>object_types.synalertss,{  nullable:false,onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'object_type_id'})
    object_type_:object_types | null;

@ManyToOne(type=>object_types, object_types=>object_types.synalertss2,{  nullable:false,onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'object_type_id'})
    object_type_:object_types | null;
```

Is this a problem with my database schema or is this a bug?

**Comment by Kononnable** [comment] 2018-07-24 20:34
Could you provide some reproduction data? It may be a bug but its hard to tell without knowing how database structures look likes.
It would be great if you could paste DDL statements for creating such tables. It could be just 2-3 tables with only relation columns(no need for full table structure) on which you encounter such behavior.

**Comment by arthurchumak** [comment] 2018-08-06 13:09
@amfsyn try this [fix](https://github.com/Kononnable/typeorm-model-generator/pull/92)

**Comment by Kononnable** [comment] 2018-09-05 19:45
@amfsyn Did @arthurchumak solution helped with your problem? Could you provide some info how to reproduce it(so it can be added to CI tests)?

**Comment by amfsyn** [comment] 2018-09-06 05:57
Sorry, I was playing with this during a downturn at work. I'll see if I can get it working this weekend.

**Comment by ndarilek** [comment] 2018-10-17 17:13
Looks like #101 might be a dupe of this. I provided a table definition there that causes duplicate entries. Maybe that can be used to test #92?

**Comment by Kononnable** [comment] 2018-12-29 20:33
Closing as no schema was provided to reproduce the issue. Might be connected to #130 .

**Closed by Kononnable** 2018-12-29 20:33 UTC
