### ISSUE TITLE
Triplicated relations

### ISSUE THREAD

**Issue by KevinGuancheDarias** [Kononnable/typeorm-model-generator#123] opened 2018-11-06 15:49 UTC
Hello @Kononnable I have almost all my entities duplicated.

I will investigate by my own, how is your mysql driver obtaining the metadata.

Example model, (I have selected the easiest model)

## DDL
```sql
CREATE TABLE `units` (
  `id` smallint(6) UNSIGNED NOT NULL,
  `type` smallint(6) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `unit_types` (
  `id` smallint(6) UNSIGNED NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `units`
  ADD CONSTRAINT `units_ibfk_1` FOREIGN KEY (`type`) REFERENCES `unit_types` (`id`),
```

As you can see only units has the FK to unit_types

## Code
```typescript
@Entity("units",{schema:"test_shit"})
@Index("name",["name",],{unique:true})
@Index("type",["type",])
@Index("improvement_id",["improvement_",])
export class units {
    @ManyToOne(type=>unit_types, unit_types=>unit_types.unitss,{ onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'type'})
    public type:unit_types | null;

    @ManyToOne(type=>unit_types, unit_types=>unit_types.unitss2,{ onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'type'})
    public type:unit_types | null;

    @ManyToOne(type=>unit_types, unit_types=>unit_types.unitss3,{ onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'type'})
    public type:unit_types | null;
}

@Entity("unit_types",{schema:"test_shit"})
@Index("name",["name",],{unique:true})
export class unit_types {
    @OneToMany(type=>units, units=>units.type,{ onDelete: 'RESTRICT' ,onUpdate: 'RESTRICT' })
    public unitss:units[];

    @OneToMany(type=>units, units=>units.type,{ onDelete: 'RESTRICT' ,onUpdate: 'RESTRICT' })
    public unitss2:units[];

    @OneToMany(type=>units, units=>units.type,{ onDelete: 'RESTRICT' ,onUpdate: 'RESTRICT' })
    public unitss3:units[];
}
```

If you have any useful information, would be really welcome!

**Comment by KevinGuancheDarias** [comment] 2018-11-06 18:22
Extra information, already triplicated in relationsTemp, I will continue investigating
```javascript
Object {ownerColumnsNames: Array(3), referencedColumnsNames: Array(3), actionOnDelete: "RESTRICT", actionOnUpdate: "RESTRICT", object_id: "units_ibfk_1", …}
actionOnDelete: "RESTRICT"
actionOnUpdate: "RESTRICT"
object_id: "units_ibfk_1"
ownerColumnsNames: Array(3) ["type", "type", "type"]
length: 3
__proto__: Array(0) [, …]
0: "type"
1: "type"
2: "type"
ownerTable: "units"
referencedColumnsNames: Array(3) ["id", "id", "id"]
length: 3
__proto__: Array(0) [, …]
0: "id"
1: "id"
2: "id"
referencedTable: "unit_types"
__proto__: Object {constructor: , __defineGetter__: , __defineSetter__: , …}
```

**Comment by KevinGuancheDarias** [comment] 2018-11-06 18:33
As you can observe in the image, it is the query returning the values, this is as of version 5.7.19 of MySQL
![image](https://user-images.githubusercontent.com/6832422/48085461-3efe7980-e1f2-11e8-9632-5ad19680f8b8.png)

**Comment by Kononnable** [comment] 2018-11-19 22:22
Sorry for long delay. I had a lot on my mind lately.
Could you replace column names in this query with `*` and paste the results? There probably should be more conditions added to join predicate to produce distinct results. I would like to try to fix this that way - adding `distinct` is an easy solution, but in my experience it can sometimes lead to more problems. If nothing suspicious is found I will gladly merge your PR.

**Comment by KevinGuancheDarias** [comment] 2018-11-29 10:37
Srry, didn't receive notification from github, I will execute later, and tell you, thanks for your help!

**Comment by Kononnable** [comment] 2018-12-13 19:13
Merged solution with `distinct` since I couldn't reproduce the exact issue.

**Closed by Kononnable** 2018-12-13 19:13 UTC
Labels: bug
